CartoSys/Models/Flow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CartoSys.Models
{
    public class Flow
    {
        public int ID { get; set; }
        public int SourceId { get; set; }
        public int TargetId { get; set; }
        public string Status { get; set; }
        public int? FlowType { get; set; }
        public string SendingMode { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }
}

CartoSys/Models/FlowType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CartoSys.Models
{
    public class FlowType
    {
        public int ID { get; set; }
        public String Description { get; set; }
    }
}

CartoSys/Models/FlowView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CartoSys.Models
{
    public class FlowView
    {
        public int ID { get; set; }
        public String SourceName { get; set; }
        public String TargetName { get; set; }
        public string Status { get; set; }
        public string FlowType { get; set; }
        public string SendingMode { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }
}

CartoSys/Controllers/FlowController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CartoSys.Models;
using System.Drawing;
using SolidBrush = MindFusion.Drawing.SolidBrush;
using LinearGradientBrush = MindFusion.Drawing.LinearGradientBrush;
using MindFusion.Diagramming;
using MindFusion.Diagramming.Mvc;
using MindFusion.Diagramming.Layout;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace CartoSys.Controllers
{
    public class FlowController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        //
        // GET: /Flow/

        public ActionResult Index()
        {
            var flowList = from f in db.Flows
                           join sa in db.Applications on f.SourceId equals sa.ID
                           join ta in db.Applications on f.TargetId equals ta.ID
                           join ft in db.FlowTypes on f.FlowType equals ft.ID into loft
                           from subft in loft.DefaultIfEmpty()
                           select new FlowView() { ID = f.ID, SourceName = sa.Name, TargetName = ta.Name, Status = f.Status, FlowType = (subft == null ? String.Empty : subft.Description), SendingMode = f.SendingMode, Code = f.Code, Description = f.Description };
            return View(flowList.ToList());
        }

        //
        // GET: /Flow/Details/5

        public ActionResult Details(int id = 0)
        {
            Flow flow = db.Flows.Find(id);
            if (flow == null)
            {
                return HttpNotFound();
            }
            return View(flow);
        }

        //
        // GET: /Flow/Create

        public ActionResult Create()
        {
            var AppLst = new List<string>();

            var appplications = from a in db.Applications
                           orderby a.Name
                           select a;
            var applicationList = new SelectList(appplications, "ID", "Name");
            //GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.applicationList = applicationList;
            //Get flow type
            var flowTypes = from ft in db.FlowTypes
                            select ft;
            ViewBag.flowTypeList = new SelectList(flowTypes, "ID", "Description");
            return View();
        }

        //
        // POST: /Flow/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flow flow)
        {
            if (ModelState.IsValid)
            {
                db.Flows.Add(flow);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(flow);
        }

        //
        // GET: /Flow/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Flow flow = db.Flows.Find(id);
            if (flow == null)
            {
                return HttpNotFound();
            }

            var AppLst = new List<string>();

            //Get application list
            var appplications = from a in db.Applications
                                orderby a.Name
                                select a;
            var applicationList = new SelectList(appplications, "ID", "Name");
            ViewBag.applicationList = applicationList;
            //Get flow type
            var flowTypes = from ft in db.FlowTypes
                            select ft;
            ViewBag.flowTypeList = new SelectList(flowTypes, "ID", "Description"); 
            
            return View(flow);
        }

        //
        // POST: /Flow/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Flow flow)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flow).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
                //return Redirect("../ClosePage.html");
                return RedirectToAction("ClosePage");
            }
            return View(flow);
        }

        //
        // GET: /Flow/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Flow flow = db.Flows.Find(id);
            if (flow == null)
            {
                return HttpNotFound();
            }
            return View(flow);
        }

        //
        // POST: /Flow/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flow flow = db.Flows.Find(id);
            db.Flows.Remove(flow);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ClosePage()
        {
            return View();
        }

        //
        // GET: /Flow/Flow1

        public ActionResult Flow1(int sourceId = 1, float zoom = 1)
        {
            
            int applicationId = sourceId;
            //Appplication list
            var AppLst = new List<string>();

            var appplications = from a in db.Applications
                                orderby a.Name
                                select a;
            var applicationList = new SelectList(appplications, "ID", "Name");
            //GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.applicationList = applicationList;

            DiagramView view = new DiagramView("diagramView1");
            view.Width = 5000;
            view.Height = 5000;

            Diagram diagram = view.Diagram;
            //diagram.Font = new Font("Verdana", 3);
            //diagram.ShapeBrush = new LinearGradientBrush(Color.LightBlue, Color.Blue, 90);
            //diagram.ShapeBrush = new LinearGradientBrush(Color.White, Color.Fuchsia, 90);

            //diagram.LinkBrush = new SolidBrush(Color.Black);
            diagram.LinkHeadShape = ArrowHeads.Triangle;
            diagram.LinkHeadShapeSize = 3;

            //Update the mouse hover distance - does not seem to work
            //diagram.MeasureUnit = GraphicsUnit.Pixel;
            diagram.LinkHitDistance = 1f;

            //Create theme for the diagram
            Theme theme = new Theme();
            //Set style for shape
            ShapeNodeStyle shapeStyle = new ShapeNodeStyle();
            shapeStyle.FontFamily = "Tahoma";
            shapeStyle.FontSize = 14;
            theme.RegisterStyle(typeof(ShapeNode), shapeStyle);
            //Set style for links
            DiagramLinkStyle linkStyle = new DiagramLinkStyle();
            linkStyle.FontFamily = "MS Sans Serif";
            linkStyle.FontSize = 6;
            theme.RegisterStyle(typeof(DiagramLink), linkStyle);
            diagram.Theme = theme;

             //Get the name of the root application
            string rootAppName = db.Applications.Find(applicationId).Name;

            //Create the box for the root application
            ShapeNode rootApplication = diagram.Factory.CreateShapeNode(new RectangleF(10, 10, 50 * zoom, 50 * zoom));
            rootApplication.Id = applicationId;
            //appli.Shape = Shape.FromId(application.ID);
            rootApplication.Text = rootAppName;
            rootApplication.Brush = new LinearGradientBrush(Color.Yellow, Color.White, 90);

            //Get all applications with link to this one
            var toApplication = from f in db.Flows
                                join a in db.Applications on f.TargetId equals a.ID
                                where f.SourceId == applicationId
                                select new { a.ID, a.Name, flowId = f.ID, f.Description, f.FlowType };
            var fromApplication = from f in db.Flows
                                  join a in db.Applications on f.SourceId equals a.ID
                                  where f.TargetId == applicationId
                                  select new { a.ID, a.Name, flowId = f.ID, f.Description, f.FlowType };

            //List unique des applications
            var singleApplicationList = (from ta in toApplication.Union(fromApplication)
                                         join a in db.Applications on ta.ID equals a.ID
                                         select new { ta.ID, ta.Name, a.Documentation }).Distinct();

            //Create applications having flows for the selected application
            foreach (var application in singleApplicationList)
            {
                ShapeNode appli = diagram.Factory.CreateShapeNode(new RectangleF(10, 10, 50 * zoom, 20 * zoom));
                appli.Id = application.ID;
                appli.Text = application.Name;
                appli.ToolTip = "<html><div width='300' style='background-color: #FFFF99; font-size: small;'>" + application.ID + '-' + application.Documentation + "</div></html>";
                appli.Brush = new LinearGradientBrush(Color.LightBlue, Color.White, 90);
            }

            //Create applications with flows to the selected application
            foreach (var application in toApplication)
            {
                DiagramLink link = diagram.Factory.CreateDiagramLink(rootApplication, diagram.FindNodeById(application.ID));
                link.Text = application.flowId.ToString() + '-' + application.Description.Substring(0, Math.Min(application.Description.Length, 20));
                //Add suspension mark to show flow description is truncated
                if (application.Description.Length > 20) { link.Text = link.Text + "..."; }
                link.ToolTip = "<html><div width='300' style='background-color: #FFFF99; font-size: small;'>" + application.flowId + '-' + application.Description + "</div></html>";

                //Set link color
                link.Pen = new MindFusion.Drawing.Pen(ColorLink(application.FlowType));


                link.HyperLink = "/Flow/Edit/" + application.flowId;

                //Do not allow link to be selected

CartoSys/Views/Flow/ClosePage.cshtml
@{
    ViewBag.Title = "ClosePage";
}

<h2>ClosePage</h2>

<script>
 //or if you prefer jQuery
 $(function(){
     //script goes here
     window.close();
 });
</script>

CartoSys/Views/Flow/Create.cshtml
@model CartoSys.Models.Flow

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Flow</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SourceId)
        </div>
        <div class="editor-field">
            @* @Html.EditorFor(model => model.SourceId) *@
            @Html.DropDownList("SourceId", ViewBag.applicationList as SelectList, "Select...")
            @Html.ValidationMessageFor(model => model.SourceId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TargetId)
        </div>
        <div class="editor-field">
            @* @Html.EditorFor(model => model.TargetId) *@
            @Html.DropDownList("TargetId", ViewBag.applicationList as SelectList, "Select...")
            @Html.ValidationMessageFor(model => model.TargetId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FlowType)
        </div>
        <div class="editor-field">
            @* @Html.EditorFor(model => model.FlowType) *@
            @Html.DropDownList("FlowType", ViewBag.flowTypeList as SelectList, "Select...")
            @Html.ValidationMessageFor(model => model.FlowType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SendingMode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SendingMode)
            @Html.ValidationMessageFor(model => model.SendingMode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Code)
            @Html.ValidationMessageFor(model => model.Code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CartoSys/Views/Flow/Delete.cshtml
@model CartoSys.Models.Flow

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Flow</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SourceId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SourceId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TargetId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TargetId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FlowType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FlowType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SendingMode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SendingMode)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CartoSys/Views/Flow/Details.cshtml
@model CartoSys.Models.Flow

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Flow</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SourceId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SourceId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TargetId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TargetId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FlowType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FlowType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SendingMode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SendingMode)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CartoSys/Views/Flow/Edit.cshtml
@model CartoSys.Models.Flow
@{ Layout = "~/Views/Shared/_ModalLayout.cshtml"; }

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Flow</legend>

        @Html.HiddenFor(model => model.ID)

        <div class ="float-left">
        <div class="editor-label">
            @Html.LabelFor(model => model.SourceId)
        </div>
        <div class="editor-field">
            @* @Html.EditorFor(model => model.SourceId) *@
            @Html.DropDownList("SourceId", ViewBag.applicationList as SelectList, "Select...")
            @Html.ValidationMessageFor(model => model.SourceId)
        </div>
        </div>

        <div class ="float-left">
        <div class="editor-label">
            @Html.LabelFor(model => model.TargetId)
        </div>
        <div class="editor-field">
            @* @Html.EditorFor(model => model.TargetId) *@
            @Html.DropDownList("TargetId", ViewBag.applicationList as SelectList, "Select...")
            @Html.ValidationMessageFor(model => model.TargetId)
        </div>
        </div>

        <div class ="" style="clear: left;">
        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status)
        </div>
        </div>

        <div style="white-space: nowrap;">
        <div class="float-left">
        <div class="editor-label">
            @Html.LabelFor(model => model.FlowType)
        </div>
        <div class="editor-field">
            @* @Html.EditorFor(model => model.FlowType) *@
            @Html.DropDownList("FlowType", ViewBag.flowTypeList as SelectList, "Select...")
            @Html.ValidationMessageFor(model => model.FlowType)
        </div>
        </div>

        <div class="float-left">
        <div class="editor-label">
            @Html.LabelFor(model => model.SendingMode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SendingMode)
            @Html.ValidationMessageFor(model => model.SendingMode)
        </div>
        </div>
        </div>

        <div style="margin-top: 60px; ">
        <div class="editor-label">
            @Html.LabelFor(model => model.Code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Code)
            @Html.ValidationMessageFor(model => model.Code)
        </div>
        </div>

        <div class="float-left">
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new {rows="6", cols="5"})
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        </div>

        <div >
            <input type="submit" value="Save"/>
            <input type="button" value="Cancel" onclick="window.close();"/>
        </div>  
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CartoSys/Views/Flow/Flow1.cshtml
@using MindFusion.Diagramming;
@using MindFusion.Diagramming.Mvc

@{
    ViewBag.Title = "Flow1";
}


@using (Html.BeginForm("Flow1","Flow",FormMethod.Get)){     
         <p>Application: @Html.DropDownList("SourceId", ViewBag.applicationList as SelectList, "Select..." ) 
             Zoom: @Html.DropDownList("Zoom", new List<SelectListItem>

                 {
                    new SelectListItem{ Text="x 0.5", Value = "0.5" },
                    new SelectListItem{ Text="x 0.75", Value = "0.75" },
                    new SelectListItem{ Text="x 1", Value = "1", Selected = true },
                    new SelectListItem{ Text="x 1.25", Value = "1.25" },
                    new SelectListItem{ Text="x 1.5", Value = "1.5" },
                    new SelectListItem{ Text="x 1.75", Value = "1.75" },
                    new SelectListItem{ Text="x 2", Value = "2" }
                 }) 
         </p> 
        } 

@Html.DiagramView((DiagramView)ViewBag.DiagramView)

<script>
    $(document).ready(function () {
        $("#SourceId").change(function () {
            $(this).closest("form").submit();
        });
        $("#Zoom").change(function () {
            $(this).closest("form").submit();
        });
    });

    function pageLoad(sender, args)
    {
        var diagram = $find('diagramView1');
        diagram.get_element().addEventListener("mousemove", Function.createDelegate(diagram, onDiagramMouseMove), false);
        currLink = null;
    }

    function onDiagramMouseMove(e)
    {
        if (currLink) {
            currLink.setShadowColor(null);
            currLink.setStrokeThickness(1);
        }
        var cursor = MindFusion.Diagramming.Utils.getCursorPos(e, this.get_element());
        var point = this.clientToDoc(cursor);
        var link = this.getLinkAt(point, true, false);
        if (link)
        {
            currLink = link;
            //alert(currLink.getPen());
            //currLink.setShadowColor('#0000FF');
            currLink.setShadowColor(currLink.getPen());
            currLink.setStrokeThickness(2);
        }
        this.invalidate();
    }

    function onLinkClicked(sender, args) {
        //window.open(args.getLink().getHyperLink(), "LinkEdit", "menubar=no, status=no, scrollbars=no, menubar=no, width=1000, height=800");
        window.showModalDialog(args.getLink().getHyperLink(), "LinkEdit", "dialogWidth:450px;dialogHeight:505px");
    }
    
</script>

CartoSys/Views/Flow/Index.cshtml
@model IEnumerable<CartoSys.Models.FlowView>

@{
    ViewBag.Title = "Flows";
}

<h2>Flows</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink("Export to Excel", "ExportToExcel")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SourceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TargetName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlowType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SendingMode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SourceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TargetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FlowType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SendingMode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>